name: PDF to Word Conversion

on:
  workflow_dispatch:
    inputs:
      pdf_url:
        description: 'URL of PDF to convert'
        required: true
      unique_id:
        description: 'Unique job ID'
        required: true
      callback_url:
        description: 'Callback URL'
        required: true

jobs:
  convert:
    runs-on: windows-latest
    timeout-minutes: 30
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r scripts/requirements.txt
        
    - name: Download PDF
      run: python scripts/download.py "${{ github.event.inputs.pdf_url }}" "${{ github.event.inputs.unique_id }}.pdf"
      
    - name: Virus Scan
      run: python scripts/virus_scan.py "${{ github.event.inputs.unique_id }}.pdf"
      
    - name: Convert to Word
      run: bin/converter.exe "${{ github.event.inputs.unique_id }}.pdf" "${{ github.event.inputs.unique_id }}.docx"
      
    - name: Upload Result
      run: python scripts/upload.py "${{ github.event.inputs.unique_id }}.docx" "${{ github.event.inputs.unique_id }}" "${{ github.event.inputs.callback_url }}"
      
    - name: Cleanup
      run: |
        del "${{ github.event.inputs.unique_id }}.pdf"
        del "${{ github.event.inputs.unique_id }}.docx"
